/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TournamentStatus = "Complete" | "Running" | "Set" | "TBD";

export interface AuthUser {
  email: string;
  email_verified: Generated<boolean>;
  hashed_password: string;
  id: string;
  join_date: Generated<Timestamp>;
  username: string;
}

export interface EmailVerificationRequest {
  code: string;
  email: string;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface Entry {
  id: Generated<number>;
  tournament_id: string;
  user_id: string;
}

export interface Match {
  a_id: string;
  a_score: Generated<number>;
  b_id: string;
  b_score: Generated<number>;
  date: Timestamp;
  format: string;
  game: string;
  id: string;
  tournament_id: string;
}

export interface Tournament {
  date: Timestamp;
  description: string;
  format: string;
  game: string;
  id: string;
  location: string;
  organizer_id: string;
  rounds: Generated<number>;
  status: Generated<TournamentStatus>;
  title: string;
}

export interface UserSession {
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface DB {
  auth_user: AuthUser;
  email_verification_request: EmailVerificationRequest;
  entry: Entry;
  match: Match;
  tournament: Tournament;
  user_session: UserSession;
}
