/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthUser {
  email: string;
  email_verified: Generated<boolean>;
  hashed_password: string;
  id: string;
  join_date: Generated<Timestamp>;
  username: string;
}

export interface EmailVerificationRequest {
  code: string;
  email: string;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface UserSession {
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface DB {
  auth_user: AuthUser;
  email_verification_request: EmailVerificationRequest;
  user_session: UserSession;
}
