/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type MatchStatus = "LOSE" | "TIE" | "WIN";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TournamentStatus = "Complete" | "Running" | "Set" | "TBD";

export interface AuthUser {
  email: string;
  email_verified: Generated<boolean>;
  hashed_password: string;
  id: string;
  join_date: Generated<Timestamp>;
  username: string;
}

export interface EmailVerificationRequest {
  code: string;
  email: string;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface Entry {
  loses: Generated<number>;
  player: string;
  ties: Generated<number>;
  tournament: string;
  wins: Generated<number>;
}

export interface Matches {
  a: string;
  b: string;
  date: Timestamp;
  id: string;
  tournament_id: string;
}

export interface Results {
  final: Generated<MatchStatus>;
  id: string;
  match: string;
  player: string;
  score: Generated<number>;
}

export interface Tournament {
  date: Timestamp;
  description: string;
  format: string;
  game: string;
  id: string;
  location: string;
  organizer_id: string;
  rounds: Generated<number>;
  status: Generated<TournamentStatus>;
  title: string;
}

export interface UserSession {
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface DB {
  auth_user: AuthUser;
  email_verification_request: EmailVerificationRequest;
  entry: Entry;
  matches: Matches;
  results: Results;
  tournament: Tournament;
  user_session: UserSession;
}
